function [II,DA] = invert3x3(AA)
%INVERT3X3 calc. the inverse for a block of 3-by-3 matrices.
%   [IA,DA] = INVERT3X3(AA) returns a set of inverses IA and
%   an array of determinants DA for the set of 3-by-3 linear 
%   systems in AA. SIZE(AA), SIZE(IA) = [3,3,N], where N is 
%   the number of linear systems. DA is an N-by-1 array of 
%   determinant values. Note that each IA(:,:,K) is an 'inc-
%   omplete inverse DET(A(:,:,K)) * A(:,:,K)^(-1) to improve
%   numerical robustness. To solve a linear system, A*X = B,
%   compute (I*B)./D, given D is non-zero. 
%
%   See also INVERT2X2

%   Darren Engwirda : 2018 --
%   Email           : darren.engwirda@columbia.edu
%   Last updated    : 03/05/2018

%---------------------------------------------- basic checks    
    if (  ~isnumeric(AA))
        error('invert3x3:incorrectInputClass' , ...
            'Incorrect input class.') ;
    end
    
%---------------------------------------------- basic checks
    if (ndims(AA) ~= +3 )
        error('invert3x3:incorrectDimensions' , ...
            'Incorrect input dimensions.');
    end
    if (size(AA,1)~= +3 || ...
        size(AA,2)~= +3 )
        error('invert3x3:incorrectDimensions' , ...
            'Incorrect input dimensions.');
    end
    
%---------------------------------------------- build inv(A)
    II = zeros(size (AA)) ;

    DA = ...
    AA(1,1,:) .* ( ...
    AA(2,2,:) .* AA(3,3,:) ... 
  - AA(2,3,:) .* AA(3,2,:) ...
        ) - ... 
    AA(1,2,:) .* ( ...
    AA(2,1,:) .* AA(3,3,:) ... 
  - AA(2,3,:) .* AA(3,1,:) ...
        ) + ...
    AA(1,3,:) .* ( ...
    AA(2,1,:) .* AA(3,2,:) ... 
  - AA(2,2,:) .* AA(3,1,:) ...
        ) ;

    II(1,1,:) = ...
    AA(3,3,:) .* AA(2,2,:) ... 
  - AA(3,2,:) .* AA(2,3,:) ;
    II(1,2,:) = ...
    AA(3,2,:) .* AA(1,3,:) ...
  - AA(3,3,:) .* AA(1,2,:) ;
    II(1,3,:) = ...
    AA(2,3,:) .* AA(1,2,:) ...
  - AA(2,2,:) .* AA(1,3,:) ;

    II(2,1,:) = ...
    AA(3,1,:) .* AA(2,3,:) ...
  - AA(3,3,:) .* AA(2,1,:) ;
    II(2,2,:) = ...
    AA(3,3,:) .* AA(1,1,:) ...
  - AA(3,1,:) .* AA(1,3,:) ;
    II(2,3,:) = ...
    AA(2,1,:) .* AA(1,3,:) ...
  - AA(2,3,:) .* AA(1,1,:) ;

    II(3,1,:) = ...
    AA(3,2,:) .* AA(2,1,:) ...
  - AA(3,1,:) .* AA(2,2,:) ;
    II(3,2,:) = ...
    AA(3,1,:) .* AA(1,2,:) ...
  - AA(3,2,:) .* AA(1,1,:) ;
    II(3,3,:) = ...
    AA(2,2,:) .* AA(1,1,:) ... 
  - AA(2,1,:) .* AA(1,2,:) ;

end



